export const sampleTable = {
  col: [
    "Date",
    "Incoming",
    "Time In",
    "Outgoing",
    "Time out",
    "No. of trip",
    "Amount",
    "Remarks",
  ],
  row: [
    {
      Date: "01-21-2025",
      Incoming: "S.VILLE/FTP",
      "Time In": "06:00",
      Outgoing: "S.VILLE/FTP",
      "Time out": "18:00",
      "No. of trip": "2",
      Amount: "650",
      Remarks: "",
    },
    {
      Date: "01-22-2025",
      Incoming: "S.VILLE/FTP",
      "Time In": "06:00",
      Outgoing: "S.VILLE/FTP",
      "Time out": "18:00",
      "No. of trip": "2",
      Amount: "650",
      Remarks: "",
    },
    {
      Date: "01-23-2025",
      Incoming: "S.VILLE/FTP",
      "Time In": "06:00",
      Outgoing: "S.VILLE/FTP",
      "Time out": "18:00",
      "No. of trip": "2",
      Amount: "650",
      Remarks: "",
    },
  ],
};
